[package]
name = "oclus-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.2", features = ["chrono", "uuid", "postgres"] }
actix-web = "4.9"
tokio = { version = "1.40", features = ["full"] }
validate = "0.6"
